In [88]:
import pandas as pd
import os
import rtree
import osmnx

In [98]:
os.listdir()

['joined_plazasq.csv',
 'joined_beach.csv',
 'Data Augmentation and Preprocessing objectives.docx',
 'CEA-33.pdf',
 'joined_pubgardn.csv',
 'Quantitative Theoretical and Conceptual Framework Use in Agricultural Education Research.pdf',
 'joined_sidewalk+othrsdwk.csv',
 '.DS_Store',
 'Deliverable 2.docx',
 'USI_II_Summer_2019_syllabus_V05_15_19.pdf',
 'Untitled.ipynb',
 'ToWalkOrNotToWalk.pdf',
 'Shapefiles',
 '04oct-Article-AET.pdf',
 'joined_planimetric.csv',
 'Data_planimetrics.ipynb',
 'NYUSampleHotspotsVsControlProcessedData20190625.xlsx',
 'joined_playsprt_swimpool.csv',
 'joined_driveway.csv',
 'NYU_capstone_VML',
 'joined_median.csv',
 'joined_parkplay.csv',
 'joined_playsprt_baseball.csv',
 'segs_275.csv',
 'joined_playsprt_football.csv',
 'Variable analysis-Robin.ipynb',
 'citiessaferbydesign_final.pdf',
 'joined_parkinglot_2000.csv',
 '.ipynb_checkpoints',
 'googleapi.py',
 'safe_streets_--_green_cities-_good_health.pdf',
 'joined_pbspothr.csv',
 'data',
 'joined_abndbldg.csv',
 'prepocessingforMerge.ipynb']

In [152]:
final_dt = pd.DataFrame(columns = ['segid','id'])
final_dt

Empty DataFrame
Columns: [segid, id]
Index: []

In [153]:

for fc in os.listdir():
    if fc.startswith('joined'):
        dt_tmp = pd.read_csv(fc)
        final_dt = pd.merge(final_dt,dt_tmp,left_on='segid',right_on='segid',how = 'outer')
final_dt = final_dt.drop(columns = 'id').fillna(0)

In [154]:
final_dt.head()

,plazasq,segid,beach,pubgardn,sidewalk,othrsdwk,playsprt_swim,driveway,median,parkplay,playsprt_baseball,playsprt_football,surfpkng,pbspothr,abndbldg
0,1.0,184.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,196.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,203.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,211.0,0.0,1.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,212.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [155]:
final_dt.columns

Index(['plazasq', 'segid', 'beach', 'pubgardn', 'sidewalk', 'othrsdwk',
       'playsprt_swim', 'driveway', 'median', 'parkplay', 'playsprt_baseball',
       'playsprt_football', 'surfpkng', 'pbspothr', 'abndbldg'],
      dtype='object')

In [156]:
final_dt['new_sidewalk'] = final_dt.sidewalk.apply(lambda x: 2 if x >=2 else x)

In [157]:
final_dt.head()

,plazasq,segid,beach,pubgardn,sidewalk,othrsdwk,playsprt_swim,driveway,median,parkplay,playsprt_baseball,playsprt_football,surfpkng,pbspothr,abndbldg,new_sidewalk
0,1.0,184.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
1,1.0,196.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
2,1.0,203.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,1.0,211.0,0.0,1.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
4,1.0,212.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0

In [158]:
final_dt.new_sidewalk.describe()

count    90802.000000
mean         1.888042
std          0.394087
min          0.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: new_sidewalk, dtype: float64

In [159]:
final_dt.drop( 'sidewalk',inplace = True,axis = 1)
final_dt.head()

,plazasq,segid,beach,pubgardn,othrsdwk,playsprt_swim,driveway,median,parkplay,playsprt_baseball,playsprt_football,surfpkng,pbspothr,abndbldg,new_sidewalk
0,1.0,184.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
1,1.0,196.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
2,1.0,203.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,1.0,211.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
4,1.0,212.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0

In [160]:
final_dt.rename(columns={'new_sidewalk':'sidewalk'},inplace = True)
final_dt

,plazasq,segid,beach,pubgardn,othrsdwk,playsprt_swim,driveway,median,parkplay,playsprt_baseball,playsprt_football,surfpkng,pbspothr,abndbldg,sidewalk
0,1.0,184.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
1,1.0,196.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
2,1.0,203.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,1.0,211.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
4,1.0,212.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
5,1.0,213.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0
6,1.0,214.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
7,1.0,215.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
8,1.0,226.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
9,1.0,227.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
10,1.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
11,1.0,238.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
12,1.0,239.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
13,1.0,306.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
14,1.0,356.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
15,1.0,362.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
16,1.0,363.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
17,1.0,364.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
18,1.0,368.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
19,1.0,369.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
20,1.0,401.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
21,1.0,416.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
22,1.0,511.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,2.0
23,1.0,517.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
24,1.0,518.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
25,1.0,519.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0
26,1.0,530.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0
27,1.0,533.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
28,1.0,534.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
29,1.0,551.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90772,0.0,70322.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90773,0.0,70324.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90774,0.0,70673.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90775,0.0,71688.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90776,0.0,72336.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90777,0.0,72402.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90778,0.0,72638.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90779,0.0,72659.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90780,0.0,73296.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90781,0.0,73603.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90782,0.0,73712.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90783,0.0,73715.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90784,0.0,75422.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90785,0.0,75522.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90786,0.0,75601.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90787,0.0,76280.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90788,0.0,77934.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90789,0.0,82432.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90790,0.0,82928.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90791,0.0,84213.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90792,0.0,84489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90793,0.0,84491.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90794,0.0,84572.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90795,0.0,85698.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90796,0.0,86873.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90797,0.0,88888.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90798,0.0,89303.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90799,0.0,90324.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90800,0.0,91297.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90801,0.0,91299.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [161]:
final_dt['playsprt'] = final_dt['playsprt_baseball'] + final_dt['playsprt_football'] + final_dt['playsprt_swim']

In [162]:
#apply on binary feature

In [163]:
def binaryfeature(feature,dt = final_dt):
    dt['tmp'] = dt[feature].apply(lambda x: 1 if x>=1 else x)
    dt[feature] = dt['tmp']
    dt.drop('tmp', inplace=True, axis = 1)
    return dt

In [164]:
featurelist = ['beach','pubgardn', 'othrsdwk','plazasq','median','surfpkng','pbspothr','abndbldg','playsprt','parkplay']
for feature in featurelist:
    final_dt = binaryfeature(feature,dt = final_dt)

In [165]:
final_dt.drop(columns = ['playsprt_baseball','playsprt_football','playsprt_swim'],inplace=True)

In [167]:
final_dt.describe()

,plazasq,segid,beach,pubgardn,othrsdwk,driveway,median,parkplay,surfpkng,pbspothr,abndbldg,sidewalk,playsprt
count,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000,90802.000000
mean,0.063886,45832.561155,0.010330,0.167772,0.119788,0.004614,0.114194,0.298749,0.143235,0.164809,0.234301,1.888042,0.198178
std,0.244552,26480.192434,0.101112,0.373665,0.324715,0.078186,0.318048,0.457712,0.350314,0.371010,0.423563,0.394087,0.398630
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22878.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
50%,0.000000,45816.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,0.000000,68809.750000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000
max,1.000000,91666.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000

In [168]:
final_dt.to_csv('joined_planimetric.csv',index=False,sep=',')